In [47]:
import numpy as np

In [48]:
MOUNT_PATH = "/run/user/1000/gvfs/smb-share:server=azlab-fs01,share=東研究室/個人work/富井/"

In [49]:
ls $MOUNT_PATH

20170807RFdata/  2017-11-24_1/  2018-01-13_1/       PYUSCT_model/
2017-11-20/      2017-12-18_1/  2018-03-30/         PYUSCT_train/
2017-11-20_2/    2018-01-10_1/  2018-04-01/         test.txt*
2017-11-22_1/    2018-01-10_2/  nb_opmap_rayleigh/  training_data.hdf5*
2017-11-23_1/    2018-01-12_1/  nb_usctsim/
2017-11-23_2/    2018-01-12_2/  optical/


In [50]:
DATA_PATH = MOUNT_PATH + "PYUSCT_train/dataset010/pca_X/" 
MODEL_PATH = MOUNT_PATH + "PYUSCT_train/dataset010/model/"

In [51]:
ls $DATA_PATH

batch1000_X0000.npy*  batch1000_X0004.npy*  batch1000_X0008.npy*
batch1000_X0001.npy*  batch1000_X0005.npy*  batch1000_X0009.npy*
batch1000_X0002.npy*  batch1000_X0006.npy*  pca_X.npy*
batch1000_X0003.npy*  batch1000_X0007.npy*  pca_y.npy*


In [52]:
X = np.load(DATA_PATH + "pca_X.npy")
y = np.load(DATA_PATH + "pca_y.npy")

In [53]:
X.shape, y.shape

((10000, 800), (10000,))

## Data split

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [56]:
X_train.shape, X_test.shape

((6700, 800), (3300, 800))

## Classification

In [57]:
from sklearn.metrics import classification_report

In [58]:
target_names = ["no edge", "edge"]

### Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
clf_l1_LR = LogisticRegression(C=20, penalty='l1', tol=0.01)
clf_l2_LR = LogisticRegression(C=20, penalty='l2', tol=0.01)

#### with L1

In [18]:
clf_l1_LR.fit(X_train, y_train)

LogisticRegression(C=20, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.01,
          verbose=0, warm_start=False)

In [19]:
y_pred = clf_l1_LR.predict(X_test)

In [20]:
print("Logistic with L1")
print(classification_report(y_test, y_pred, target_names=target_names))

Logistic with L1
             precision    recall  f1-score   support

    no edge       0.92      0.86      0.89      1572
       edge       0.88      0.94      0.91      1728

avg / total       0.90      0.90      0.90      3300



#### with L2

In [21]:
clf_l2_LR.fit(X_train, y_train)

LogisticRegression(C=20, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.01,
          verbose=0, warm_start=False)

In [22]:
y_pred = clf_l2_LR.predict(X_test)

In [23]:
print("Logistic with L2")
print(classification_report(y_test, y_pred, target_names=target_names))

Logistic with L2
             precision    recall  f1-score   support

    no edge       0.94      0.85      0.89      1572
       edge       0.88      0.95      0.91      1728

avg / total       0.91      0.90      0.90      3300



### SVM/RVM

In [24]:
from sklearn import svm

In [25]:
clf_svm_rbf = svm.SVC(kernel='rbf')
clf_svm_linear = svm.SVC(kernel='linear')
clf_svm_sigmoid = svm.SVC(kernel='sigmoid')

#### rbf kernel

In [26]:
clf_svm_rbf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
y_pred = clf_svm_rbf.predict(X_test)

In [28]:
print("SVM with rbf kernel")
print(classification_report(y_test, y_pred, target_names=target_names))

SVM with rbf kernel
             precision    recall  f1-score   support

    no edge       1.00      0.06      0.12      1572
       edge       0.54      1.00      0.70      1728

avg / total       0.76      0.55      0.42      3300



#### linear kernel

In [29]:
clf_svm_linear.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
y_pred = clf_svm_linear.predict(X_test)

In [31]:
print("SVM with linear kernel")
print(classification_report(y_test, y_pred, target_names=target_names))

SVM with linear kernel
             precision    recall  f1-score   support

    no edge       0.96      0.78      0.86      1572
       edge       0.83      0.97      0.89      1728

avg / total       0.89      0.88      0.88      3300



#### sigmoid kernel

In [32]:
clf_svm_sigmoid.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
y_pred = clf_svm_sigmoid.predict(X_test)

In [34]:
print("SVM with sigmoid kernel")
print(classification_report(y_test, y_pred, target_names=target_names))

SVM with sigmoid kernel
             precision    recall  f1-score   support

    no edge       1.00      0.04      0.08      1572
       edge       0.53      1.00      0.70      1728

avg / total       0.76      0.54      0.40      3300



### Gaussian Process Regression

In [37]:
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process.kernels import WhiteKernel, ExpSineSquared

In [ ]:
from sklearn.gaussian_process import GaussianProcessRegressor

In [ ]:
gp_kernel = ExpSineSquared(1.0, 5.0, periodicity_bounds=(1e-2, 1e1)) \
    + WhiteKernel(1e-1)
iso_kernel = 1.0 * RBF([1.0])

In [ ]:
gpr = GaussianProcessRegressor(kernel=iso_kernel)

In [ ]:
y_train.dtype

In [ ]:
gpr.fit(X_train, y_train)

In [ ]:
y_pred = gpr.predict(X_test)

In [ ]:
y_pred[:10]

In [ ]:
y_test[:10]

In [ ]:
from sklearn.metrics import explained_variance_score
print("Gaussian Process Regression with isotropic rbf kernel")
print(explained_variance_score(y_test, y_pred))

### Gaussian Process Classification

In [35]:
from sklearn.gaussian_process import GaussianProcessClassifier

#### Isotropic kernel

In [185]:
clf_GPC_rbf_iso = GaussianProcessClassifier(1.0 * RBF([0.1]))

In [186]:
clf_GPC_rbf_iso.fit(X_train, y_train)

GaussianProcessClassifier(copy_X_train=True,
             kernel=1**2 * RBF(length_scale=0.1), max_iter_predict=100,
             multi_class='one_vs_rest', n_jobs=1, n_restarts_optimizer=0,
             optimizer='fmin_l_bfgs_b', random_state=None,
             warm_start=False)

In [187]:
y_pred = clf_GPC_rbf_iso.predict(X_test)

In [188]:
print("Gaussian Process Classification with isotropic rbf kernel")
print(classification_report(y_test, y_pred, target_names=target_names))

Gaussian Process Classification with isotropic rbf kernel
             precision    recall  f1-score   support

    no edge       0.97      0.89      0.93      1572
       edge       0.91      0.97      0.94      1728

avg / total       0.94      0.93      0.93      3300



1000 samples 94 -> 83
0.0...01~1000 * RBF([0.1~1000] -> 83
1 * RBF([0.01] -> 61
1 * RBF([10000] -> 36


#### Anisotropic rbf kernel

In [60]:
%ls $MODEL_PATH

clf_GPC_rbf_iso.pkl*  pca1000.pkl*


In [61]:
### load pca list
import pickle
from sklearn.externals import joblib
from sklearn.decomposition import PCA

pca = joblib.load(MODEL_PATH + "pca1000.pkl")
print("PCA model loaded.")

PCA model loaded.


/home/yuhui/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/sklearn/base.py:312: UserWarning: Trying to unpickle estimator PCA from version 0.19.1 when using version 0.19.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [189]:
weights = pca.explained_variance_ratio_
weights.shape

(800,)

In [190]:
weights[:10]

array([ 0.06531469,  0.05477736,  0.04021434,  0.03476161,  0.03281457,
        0.03119269,  0.0275882 ,  0.02456331,  0.02282751,  0.02238703])

In [191]:
from sklearn import preprocessing

In [192]:
min_max_scaler = preprocessing.MinMaxScaler()

In [197]:
weights.reshape(1,-1)

array([[  6.53146858e-02,   5.47773632e-02,   4.02143372e-02,
          3.47616116e-02,   3.28145699e-02,   3.11926870e-02,
          2.75882004e-02,   2.45633068e-02,   2.28275115e-02,
          2.23870320e-02,   1.93176516e-02,   1.42627493e-02,
          1.34231369e-02,   1.21498472e-02,   1.18588110e-02,
          1.16877185e-02,   1.10768017e-02,   1.08079307e-02,
          9.51146334e-03,   8.77772822e-03,   8.52401133e-03,
          8.25080680e-03,   7.52305215e-03,   7.11040802e-03,
          6.92245764e-03,   6.27295497e-03,   6.17033637e-03,
          6.08176622e-03,   5.62575143e-03,   5.23524627e-03,
          5.18986541e-03,   5.04232368e-03,   5.02965600e-03,
          4.83826337e-03,   4.79821863e-03,   4.64635358e-03,
          4.55105205e-03,   4.49643801e-03,   4.44708305e-03,
          4.30950083e-03,   4.19955356e-03,   3.83410408e-03,
          3.77402226e-03,   3.71213046e-03,   3.65476039e-03,
          3.55627953e-03,   3.52582940e-03,   3.37680606e-03,
        

In [198]:
weights_scaler = min_max_scaler.fit_transform(weights.reshape(-1,1))

In [200]:
weights_normal= weights_scaler.flatten()

In [205]:
tmp = -np.log(weights)

In [206]:
tmp

array([  2.72853837,   2.90447825,   3.2135317 ,   3.35924161,
         3.41688266,   3.4675716 ,   3.59036712,   3.70650154,
         3.77978882,   3.79927342,   3.94673601,   4.25010409,
         4.31077543,   4.41043868,   4.43468414,   4.44921669,
         4.5029023 ,   4.52747509,   4.65525754,   4.73553765,
         4.76486824,   4.79744429,   4.88978335,   4.94619565,
         4.97298442,   5.07150775,   5.08800192,   5.10246013,
         5.18040075,   5.25234139,   5.26104752,   5.28988826,
         5.29240369,   5.33119943,   5.33951055,   5.37167254,
         5.39239685,   5.40446975,   5.41550689,   5.4469332 ,
         5.47277706,   5.56381949,   5.57961393,   5.59614932,
         5.61172474,   5.63904036,   5.64763958,   5.69082497,
         5.70644021,   5.71542841,   5.72811464,   5.75314557,
         5.76560756,   5.7839514 ,   5.79570423,   5.80535462,
         5.82120642,   5.8455776 ,   5.85610194,   5.86789734,
         5.88671558,   5.89507485,   5.91091059,   5.91

#### balanced shuffle

In [75]:
mX, my = X_train[::6], y_train[::6]

In [207]:
len(my)

1117

In [208]:
my.sum()

587.0

In [209]:
clf_GPC_rbf_ani = GaussianProcessClassifier(1.0 * RBF(tmp))

In [ ]:
clf_GPC_rbf_ani.fit(mX, my)

In [ ]:
y_pred = clf_GPC_rbf_ani.predict(X_test)

In [ ]:
print("Gaussian Process Classification with anisotropic rbf kernel")
print(classification_report(y_test, y_pred, target_names=target_names))

### Ensemble method

####  Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf_RF = RandomForestClassifier()

In [ ]:
clf_RF.fit(X_train, y_train)

In [ ]:
y_pred = clf_RF.predict(X_test)

In [ ]:
print("Random Forest Classifier")
print(classification_report(y_test, y_pred, target_names=target_names))

#### Adboost

In [20]:
from sklearn.ensemble import AdaBoostClassifier

In [21]:
clf_Adb = AdaBoostClassifier()

In [22]:
clf_Adb.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [23]:
y_pred = clf_Adb.predict(X_test)

In [24]:
print("AdaBoost Classifier")
print(classification_report(y_test, y_pred, target_names=target_names))

AdaBoost Classifier
             precision    recall  f1-score   support

    no edge       0.78      0.68      0.72      1564
       edge       0.74      0.82      0.78      1736

avg / total       0.76      0.76      0.75      3300



#### XGBoost

In [25]:
from xgboost import XGBClassifier

In [26]:
clf_XGb = XGBClassifier()

In [27]:
clf_XGb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [28]:
y_pred = clf_XGb.predict(X_test)

In [29]:
print("XGBoost Classifier")
print(classification_report(y_test, y_pred, target_names=target_names))

XGBoost Classifier
             precision    recall  f1-score   support

    no edge       0.92      0.75      0.83      1564
       edge       0.81      0.94      0.87      1736

avg / total       0.86      0.85      0.85      3300



### Load model

In [43]:
from sklearn.externals import joblib

In [3]:
model_clf= joblib.load("clf_GPC_rbf_iso.pkl")

### Save model

In [ ]:
from sklearn.externals import joblib

In [44]:
FPATH = MODEL_PATH
FPATH

'/run/user/1000/gvfs/smb-share:server=azlab-fs01,share=東研究室/個人work/富井/PYUSCT_train/dataset010/model/'

In [45]:
model_clf = clf_GPC_rbf_iso
model_name = "clf_GPC_rbf_iso"

In [46]:
joblib.dump(model_clf, FPATH + model_name + ".pkl") 

['/run/user/1000/gvfs/smb-share:server=azlab-fs01,share=東研究室/個人work/富井/PYUSCT_train/dataset010/model/clf_GPC_rbf_iso.pkl']